#!/usr/bin/env bash
# To install Nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
