#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
