#!/usr/bin/env bash
#Install nginx on
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo rm /var/www/html/index.nginx-debian.html
sudo chown $USER:$USER /var/www/html
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-enabled/default

sudo service nginx restart
